package com.retail.jiratracker;

public interface JiraTrackerQueryConstants {
	
	 String APPLICATION_JSON_TYPE = "application/json";
	 final String getAllTicketsSql="SELECT TICKET.TICKETID,TICKET.TICKETSUMMARY,TICKET.TICKETDETAILS,TICKET.TICKETSTATUS FROM T_TICKET";
	 final String getAllTicketsPerReleaseSql="SELECT TICKET.TICKETID,TICKET.TICKETSUMMARY,TICKET.TICKETDETAILS,TICKET.TICKETSTATUS FROM T_TICKET WHERE TARGETRELEASE=?";
	 final String addNewTicketSql="INSERT INTO T_TICKET(TICKETID,TICKETSUMMARY,TICKETDETAILS,TICKETSTATUS,CREATEDDATE,UPDATEDDATE,ASSIGNEDDATE,ENDDATE,PRIORITY,TARGETRELEASE,ASSIGNEDTO) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
	 final String changeTicketStatusSql="UPDATE T_TICKET SET TICKETSTATUS=? WHERE TICKETID=?";
	 final String assignTicketToUserSql="UPDATE T_TICKET SET ASSIGNTO=? WHERE TICKETID=?";
	 final String deleteRejectedTicketsSql="DELETE FROM T_TICKET WHERE TICKETSTATUS='REJECTED' ";
}
